"""Initial migration

Revision ID: 9b06b50c123a
Revises: None
Create Date: 2026-06-10 13:35:28.518954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9b06b50c123a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pdf_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('temp_path', sa.String(), nullable=True),
    sa.Column('pdf_type', sa.Enum('POLYSOMNOGRAPHIE', 'POLYGRAPHIE_PPC', 'EFR_STANDARD', 'EFR_AVANCEE', 'UNKNOWN', name='pdftype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='pdfstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_files_id'), 'pdf_files', ['id'], unique=False)
    op.create_table('efr_avancees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_nom', sa.String(), nullable=True),
    sa.Column('patient_prenom', sa.String(), nullable=True),
    sa.Column('patient_dob', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('date_examen', sa.String(), nullable=True),
    sa.Column('medecin', sa.String(), nullable=True),
    sa.Column('clinique', sa.String(), nullable=True),
    sa.Column('cv_lente', sa.Float(), nullable=True),
    sa.Column('vt', sa.Float(), nullable=True),
    sa.Column('vre', sa.Float(), nullable=True),
    sa.Column('ci', sa.Float(), nullable=True),
    sa.Column('ce', sa.Float(), nullable=True),
    sa.Column('sgaw', sa.Float(), nullable=True),
    sa.Column('gaw', sa.Float(), nullable=True),
    sa.Column('sraw', sa.Float(), nullable=True),
    sa.Column('raw', sa.Float(), nullable=True),
    sa.Column('vgt_raw', sa.Float(), nullable=True),
    sa.Column('vgt_plethysmo', sa.Float(), nullable=True),
    sa.Column('cpt_plethysmo', sa.Float(), nullable=True),
    sa.Column('vr_plethysmo', sa.Float(), nullable=True),
    sa.Column('cv_cpt', sa.Float(), nullable=True),
    sa.Column('vre_cpt', sa.Float(), nullable=True),
    sa.Column('cvf', sa.Float(), nullable=True),
    sa.Column('vems', sa.Float(), nullable=True),
    sa.Column('vems_cvf_pct', sa.Float(), nullable=True),
    sa.Column('dep', sa.Float(), nullable=True),
    sa.Column('dem', sa.Float(), nullable=True),
    sa.Column('dlco', sa.Float(), nullable=True),
    sa.Column('dlco_pct', sa.Float(), nullable=True),
    sa.Column('kco', sa.Float(), nullable=True),
    sa.Column('kco_pct', sa.Float(), nullable=True),
    sa.Column('vi', sa.Float(), nullable=True),
    sa.Column('va', sa.Float(), nullable=True),
    sa.Column('interpretation_texte', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efr_avancees_id'), 'efr_avancees', ['id'], unique=False)
    op.create_table('efr_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_nom', sa.String(), nullable=True),
    sa.Column('patient_prenom', sa.String(), nullable=True),
    sa.Column('patient_dob', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('date_examen', sa.String(), nullable=True),
    sa.Column('medecin', sa.String(), nullable=True),
    sa.Column('clinique', sa.String(), nullable=True),
    sa.Column('tabagisme', sa.String(), nullable=True),
    sa.Column('cvf_pre', sa.Float(), nullable=True),
    sa.Column('cvf_post', sa.Float(), nullable=True),
    sa.Column('cvf_pct_ref', sa.Float(), nullable=True),
    sa.Column('vems_pre', sa.Float(), nullable=True),
    sa.Column('vems_post', sa.Float(), nullable=True),
    sa.Column('vems_pct_ref', sa.Float(), nullable=True),
    sa.Column('vems_cvf_pre', sa.Float(), nullable=True),
    sa.Column('vems_cvf_post', sa.Float(), nullable=True),
    sa.Column('dep_pre', sa.Float(), nullable=True),
    sa.Column('dep_post', sa.Float(), nullable=True),
    sa.Column('dep_pct_ref', sa.Float(), nullable=True),
    sa.Column('dem25_75_pre', sa.Float(), nullable=True),
    sa.Column('dem25_75_post', sa.Float(), nullable=True),
    sa.Column('dem75_pre', sa.Float(), nullable=True),
    sa.Column('dem25_pre', sa.Float(), nullable=True),
    sa.Column('dem50_pre', sa.Float(), nullable=True),
    sa.Column('cpt', sa.Float(), nullable=True),
    sa.Column('vr', sa.Float(), nullable=True),
    sa.Column('vr_cpt_pct', sa.Float(), nullable=True),
    sa.Column('rva_tot', sa.Float(), nullable=True),
    sa.Column('srva_tot', sa.Float(), nullable=True),
    sa.Column('reversibilite_bronchique', sa.Boolean(), nullable=True),
    sa.Column('traitement_utilise', sa.String(), nullable=True),
    sa.Column('interpretation_texte', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efr_standards_id'), 'efr_standards', ['id'], unique=False)
    op.create_table('polygraphie_ppcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_nom', sa.String(), nullable=True),
    sa.Column('patient_prenom', sa.String(), nullable=True),
    sa.Column('patient_dob', sa.String(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('date_enregistrement', sa.String(), nullable=True),
    sa.Column('iah_residuel', sa.Float(), nullable=True),
    sa.Column('ido', sa.Float(), nullable=True),
    sa.Column('iah_dorsal', sa.Float(), nullable=True),
    sa.Column('iah_non_dorsal', sa.Float(), nullable=True),
    sa.Column('apnees_obstructives_nb', sa.Integer(), nullable=True),
    sa.Column('apnees_centrales_nb', sa.Integer(), nullable=True),
    sa.Column('hypopnees_nb', sa.Integer(), nullable=True),
    sa.Column('spo2_moyenne', sa.Float(), nullable=True),
    sa.Column('spo2_minimale', sa.Float(), nullable=True),
    sa.Column('duree_spo2_sous_90_pct', sa.Float(), nullable=True),
    sa.Column('pression_mediane', sa.Float(), nullable=True),
    sa.Column('pression_moyenne', sa.Float(), nullable=True),
    sa.Column('pression_p95', sa.Float(), nullable=True),
    sa.Column('efficacite_sommeil_pct', sa.Float(), nullable=True),
    sa.Column('severite_residuelle', sa.String(), nullable=True),
    sa.Column('conclusion_texte', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polygraphie_ppcs_id'), 'polygraphie_ppcs', ['id'], unique=False)
    op.create_table('polysomnographies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_nom', sa.String(), nullable=True),
    sa.Column('patient_prenom', sa.String(), nullable=True),
    sa.Column('patient_dob', sa.String(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('date_enregistrement', sa.String(), nullable=True),
    sa.Column('debut_enregistrement', sa.String(), nullable=True),
    sa.Column('fin_enregistrement', sa.String(), nullable=True),
    sa.Column('iah', sa.Float(), nullable=True),
    sa.Column('ido', sa.Float(), nullable=True),
    sa.Column('charge_hypoxique', sa.Float(), nullable=True),
    sa.Column('iah_obstructif', sa.Float(), nullable=True),
    sa.Column('iah_central', sa.Float(), nullable=True),
    sa.Column('iah_mixte', sa.Float(), nullable=True),
    sa.Column('iah_dorsal', sa.Float(), nullable=True),
    sa.Column('iah_non_dorsal', sa.Float(), nullable=True),
    sa.Column('apnees_obstructives_nb', sa.Integer(), nullable=True),
    sa.Column('apnees_centrales_nb', sa.Integer(), nullable=True),
    sa.Column('apnees_mixtes_nb', sa.Integer(), nullable=True),
    sa.Column('hypopnees_nb', sa.Integer(), nullable=True),
    sa.Column('duree_moyenne_apnees', sa.Float(), nullable=True),
    sa.Column('duree_apnee_plus_longue', sa.Float(), nullable=True),
    sa.Column('spo2_moyenne', sa.Float(), nullable=True),
    sa.Column('spo2_minimale', sa.Float(), nullable=True),
    sa.Column('duree_spo2_sous_90_pct', sa.Float(), nullable=True),
    sa.Column('charge_hypoxique_valeur', sa.Float(), nullable=True),
    sa.Column('index_desaturations', sa.Float(), nullable=True),
    sa.Column('nb_desaturations', sa.Integer(), nullable=True),
    sa.Column('tts_min', sa.Float(), nullable=True),
    sa.Column('efficacite_sommeil_pct', sa.Float(), nullable=True),
    sa.Column('latence_endormissement_min', sa.Float(), nullable=True),
    sa.Column('latence_rem_min', sa.Float(), nullable=True),
    sa.Column('n1_min', sa.Float(), nullable=True),
    sa.Column('n2_min', sa.Float(), nullable=True),
    sa.Column('n3_min', sa.Float(), nullable=True),
    sa.Column('rem_min', sa.Float(), nullable=True),
    sa.Column('eveil_intra_min', sa.Float(), nullable=True),
    sa.Column('micro_eveils_nb', sa.Integer(), nullable=True),
    sa.Column('micro_eveils_index', sa.Float(), nullable=True),
    sa.Column('mpjs_nb', sa.Integer(), nullable=True),
    sa.Column('mpjs_index', sa.Float(), nullable=True),
    sa.Column('ronflements_pct', sa.Float(), nullable=True),
    sa.Column('volume_audio_moyen', sa.Float(), nullable=True),
    sa.Column('volume_audio_max', sa.Float(), nullable=True),
    sa.Column('severite', sa.String(), nullable=True),
    sa.Column('conclusion_texte', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=False),
    sa.Column('medecin', sa.String(), nullable=True),
    sa.Column('clinique', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polysomnographies_id'), 'polysomnographies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_polysomnographies_id'), table_name='polysomnographies')
    op.drop_table('polysomnographies')
    op.drop_index(op.f('ix_polygraphie_ppcs_id'), table_name='polygraphie_ppcs')
    op.drop_table('polygraphie_ppcs')
    op.drop_index(op.f('ix_efr_standards_id'), table_name='efr_standards')
    op.drop_table('efr_standards')
    op.drop_index(op.f('ix_efr_avancees_id'), table_name='efr_avancees')
    op.drop_table('efr_avancees')
    op.drop_index(op.f('ix_pdf_files_id'), table_name='pdf_files')
    op.drop_table('pdf_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
