from sqlalchemy import Column, Integer, String, Float, Boolean, ForeignKey, Text
from app.database import Base

class EFRStandard(Base):
    __tablename__ = "efr_standards"
    id = Column(Integer, primary_key=True, index=True)
    patient_nom = Column(String, nullable=True)
    patient_prenom = Column(String, nullable=True)
    patient_dob = Column(String, nullable=True)
    genre = Column(String, nullable=True)
    taille = Column(Float, nullable=True)
    poids = Column(Float, nullable=True)
    imc = Column(Float, nullable=True)
    date_examen = Column(String, nullable=True)
    medecin = Column(String, nullable=True)
    clinique = Column(String, nullable=True)
    tabagisme = Column(String, nullable=True)
    cvf_pre = Column(Float, nullable=True)
    cvf_post = Column(Float, nullable=True)
    cvf_pct_ref = Column(Float, nullable=True)
    vems_pre = Column(Float, nullable=True)
    vems_post = Column(Float, nullable=True)
    vems_pct_ref = Column(Float, nullable=True)
    vems_cvf_pre = Column(Float, nullable=True)
    vems_cvf_post = Column(Float, nullable=True)
    dep_pre = Column(Float, nullable=True)
    dep_post = Column(Float, nullable=True)
    dep_pct_ref = Column(Float, nullable=True)
    dem25_75_pre = Column(Float, nullable=True)
    dem25_75_post = Column(Float, nullable=True)
    dem75_pre = Column(Float, nullable=True)
    dem25_pre = Column(Float, nullable=True)
    dem50_pre = Column(Float, nullable=True)
    cpt = Column(Float, nullable=True)
    vr = Column(Float, nullable=True)
    vr_cpt_pct = Column(Float, nullable=True)
    rva_tot = Column(Float, nullable=True)
    srva_tot = Column(Float, nullable=True)
    reversibilite_bronchique = Column(Boolean, nullable=True)
    traitement_utilise = Column(String, nullable=True)
    interpretation_texte = Column(Text, nullable=True)
    pdf_file_id = Column(Integer, ForeignKey("pdf_files.id", ondelete="CASCADE"), nullable=False)
