from sqlalchemy import Column, Integer, String, Float, ForeignKey, Text
from app.database import Base

class EFRAvancee(Base):
    __tablename__ = "efr_avancees"
    id = Column(Integer, primary_key=True, index=True)
    patient_nom = Column(String, nullable=True)
    patient_prenom = Column(String, nullable=True)
    patient_dob = Column(String, nullable=True)
    genre = Column(String, nullable=True)
    taille = Column(Float, nullable=True)
    poids = Column(Float, nullable=True)
    imc = Column(Float, nullable=True)
    date_examen = Column(String, nullable=True)
    medecin = Column(String, nullable=True)
    clinique = Column(String, nullable=True)
    cv_lente = Column(Float, nullable=True)
    vt = Column(Float, nullable=True)
    vre = Column(Float, nullable=True)
    ci = Column(Float, nullable=True)
    ce = Column(Float, nullable=True)
    sgaw = Column(Float, nullable=True)
    gaw = Column(Float, nullable=True)
    sraw = Column(Float, nullable=True)
    raw = Column(Float, nullable=True)
    vgt_raw = Column(Float, nullable=True)
    vgt_plethysmo = Column(Float, nullable=True)
    cpt_plethysmo = Column(Float, nullable=True)
    vr_plethysmo = Column(Float, nullable=True)
    cv_cpt = Column(Float, nullable=True)
    vre_cpt = Column(Float, nullable=True)
    cvf = Column(Float, nullable=True)
    vems = Column(Float, nullable=True)
    vems_cvf_pct = Column(Float, nullable=True)
    dep = Column(Float, nullable=True)
    dem = Column(Float, nullable=True)
    dlco = Column(Float, nullable=True)
    dlco_pct = Column(Float, nullable=True)
    kco = Column(Float, nullable=True)
    kco_pct = Column(Float, nullable=True)
    vi = Column(Float, nullable=True)
    va = Column(Float, nullable=True)
    interpretation_texte = Column(Text, nullable=True)
    pdf_file_id = Column(Integer, ForeignKey("pdf_files.id", ondelete="CASCADE"), nullable=False)
