from sqlalchemy import Column, Integer, String, Float, ForeignKey, Text
from app.database import Base

class Polysomnographie(Base):
    __tablename__ = "polysomnographies"
    id = Column(Integer, primary_key=True, index=True)
    patient_nom = Column(String, nullable=True)
    patient_prenom = Column(String, nullable=True)
    patient_dob = Column(String, nullable=True)
    patient_age = Column(Integer, nullable=True)
    taille = Column(Float, nullable=True)
    poids = Column(Float, nullable=True)
    imc = Column(Float, nullable=True)
    date_enregistrement = Column(String, nullable=True)
    debut_enregistrement = Column(String, nullable=True)
    fin_enregistrement = Column(String, nullable=True)
    iah = Column(Float, nullable=True)
    ido = Column(Float, nullable=True)
    charge_hypoxique = Column(Float, nullable=True)
    iah_obstructif = Column(Float, nullable=True)
    iah_central = Column(Float, nullable=True)
    iah_mixte = Column(Float, nullable=True)
    iah_dorsal = Column(Float, nullable=True)
    iah_non_dorsal = Column(Float, nullable=True)
    apnees_obstructives_nb = Column(Integer, nullable=True)
    apnees_centrales_nb = Column(Integer, nullable=True)
    apnees_mixtes_nb = Column(Integer, nullable=True)
    hypopnees_nb = Column(Integer, nullable=True)
    duree_moyenne_apnees = Column(Float, nullable=True)
    duree_apnee_plus_longue = Column(Float, nullable=True)
    spo2_moyenne = Column(Float, nullable=True)
    spo2_minimale = Column(Float, nullable=True)
    duree_spo2_sous_90_pct = Column(Float, nullable=True)
    charge_hypoxique_valeur = Column(Float, nullable=True)
    index_desaturations = Column(Float, nullable=True)
    nb_desaturations = Column(Integer, nullable=True)
    tts_min = Column(Float, nullable=True)
    efficacite_sommeil_pct = Column(Float, nullable=True)
    latence_endormissement_min = Column(Float, nullable=True)
    latence_rem_min = Column(Float, nullable=True)
    n1_min = Column(Float, nullable=True)
    n2_min = Column(Float, nullable=True)
    n3_min = Column(Float, nullable=True)
    rem_min = Column(Float, nullable=True)
    eveil_intra_min = Column(Float, nullable=True)
    micro_eveils_nb = Column(Integer, nullable=True)
    micro_eveils_index = Column(Float, nullable=True)
    mpjs_nb = Column(Integer, nullable=True)
    mpjs_index = Column(Float, nullable=True)
    ronflements_pct = Column(Float, nullable=True)
    volume_audio_moyen = Column(Float, nullable=True)
    volume_audio_max = Column(Float, nullable=True)
    severite = Column(String, nullable=True)
    conclusion_texte = Column(Text, nullable=True)
    pdf_file_id = Column(Integer, ForeignKey("pdf_files.id", ondelete="CASCADE"), nullable=False)
    medecin = Column(String, nullable=True)
    clinique = Column(String, nullable=True)
